qsub -v "datadir=/scratch1/basill/data/cutnorm_15, modeldir=/scratch1/basill/models/models_15, windowsize=15" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_30, modeldir=/scratch1/basill/models/models_30, windowsize=30" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_45, modeldir=/scratch1/basill/models/models_45, windowsize=45" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_60, modeldir=/scratch1/basill/models/models_60, windowsize=60" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_75, modeldir=/scratch1/basill/models/models_75, windowsize=75" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_90, modeldir=/scratch1/basill/models/models_90, windowsize=90" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_105, modeldir=/scratch1/basill/models/models_105, windowsize=105" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_120, modeldir=/scratch1/basill/models/models_120, windowsize=120" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_135, modeldir=/scratch1/basill/models/models_135, windowsize=135" pbs/1reg_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_150, modeldir=/scratch1/basill/models/models_150, windowsize=150" pbs/1reg_test.pbs