#/bin/bash
#PBS -N basill_big_train
#PBS -l select=1:ncpus=16:mem=125gb:ngpus=1:gpu_model=p100
#PBS -l walltime=72:00:00
#PBS -e /home/basill/pedometer/palmetto/job_output
#PBS -o /home/basill/pedometer/palmetto/job_output

module load cuda/10.2.89-gcc/8.3.1 cudnn/8.0.0.180-10.2-linux-x64-gcc/8.3.1 anaconda3/2019.10-gcc/8.3.1

source activate tf_env
cd
cd pedometer/training/

python3 train_model.py /scratch1/basill/data/training75_ALL_ALL_norm.txt 75 1 training75_ALL_ALL_model.h5
