qsub -v "datadir=/scratch1/basill/data/cutnorm_15, modeldir=/scratch1/basill/modelsweighted/models_15, windowsize=15" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_30, modeldir=/scratch1/basill/modelsweighted/models_30, windowsize=30" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_45, modeldir=/scratch1/basill/modelsweighted/models_45, windowsize=45" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_60, modeldir=/scratch1/basill/modelsweighted/models_60, windowsize=60" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_75, modeldir=/scratch1/basill/modelsweighted/models_75, windowsize=75" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_90, modeldir=/scratch1/basill/modelsweighted/models_90, windowsize=90" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_105, modeldir=/scratch1/basill/modelsweighted/models_105, windowsize=105" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_120, modeldir=/scratch1/basill/modelsweighted/models_120, windowsize=120" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_135, modeldir=/scratch1/basill/modelsweighted/models_135, windowsize=135" pbs/kfold_test.pbs
qsub -v "datadir=/scratch1/basill/data/cutnorm_150, modeldir=/scratch1/basill/modelsweighted/models_150, windowsize=150" pbs/kfold_test.pbs